{
 "title": "PG Cluster",
 "description": "Postgres Cluster Level Dashboard",
 "tags": [
  "PG",
  "Cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": "label_values(pg_up, cls)" },
   {
    "name": "ins",
    "label": "Instance",
    "query": "label_values(pg_up{job=\"pg\",cls=~\"$cls\", ins=~\".*primary.*\"},ins)"
   },
   {
    "name": "sequence",
    "label": "Sequence",
    "query": "label_values(pg_up{ins=\"$ins\"}, ins)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(pg_up{ins=\"$ins\"}, ins)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pg_up{job=\"pg\"},ins)"
   },
   {
    "name": "ip",
    "label": "IP",
    "query": "label_values(pg_up{ins=\"$ins\"} , ip)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_database_size{ins=\"$ins\"}, datname)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster ID",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_meta_info{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count without () (pg_up{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Members",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "(pg_up{cls=\"$cls\"} * 2) +  (1 - pg_in_recovery{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_database_size{cls=\"$cls\" , datname!~\"template0|template1\"})"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pg_checkpoint_tli{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count without () (pg_meta_info{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Cluster Leader",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_in_recovery{cls=\"$cls\"} == 0 and pg_up{cls=\"$cls\"} == 1"
    }
   ]
  },
  {
   "title": "Partition",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((pg_up{cls=\"$cls\"} * 2) +  (1 - pg_in_recovery{cls=\"$cls\"}) == 3)"
    }
   ]
  },
  {
   "title": "Master & Bridge",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count(pg_repl_lsn{ins=~\"\\\\d+\\\\.$cls\", state=\"streaming\"}) by (ip, ins) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pg_up{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Primary",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pg_up{cls=\"$cls\", role=\"primary\"})"
    }
   ]
  },
  {
   "title": "Standby",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pg_up{cls=\"$cls\", role=\"standby\"})"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pg_up{cls=\"$cls\", role=\"offline\"})"
    }
   ]
  },
  {
   "title": "Recovering",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pg_standby_last_lsn{cls=\"$cls\", ins!=\"$ins\", status=\"streaming\"})"
    }
   ]
  },
  {
   "title": "Direct",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pg_repl_lsn{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Bridge",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(pg_repl_lsn{cls=\"$cls\", state=\"streaming\", ins!=\"$ins\"} - pg_repl_replay_lsn{cls=\"$cls\", state=\"streaming\", ins!~\"$ins\"}) by (ins))"
    }
   ]
  },
  {
   "title": "Cascade",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pg_repl_lsn{cls=\"$cls\", state=\"streaming\", ins!=\"$ins\"})"
    }
   ]
  },
  {
   "title": "M CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node:instance:cpu_usage{cls=\"$cls\", role=\"primary\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "CPU Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "M QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgb:instance:qps{cls=\"$cls\", role=\"primary\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "M TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg:instance:tps{cls=\"$cls\", role=\"primary\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "M RT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "pgb:instance:rt{cls=\"$cls\", role=\"primary\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Disk Free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "M Backends",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_db_numbackends{ins=\"$ins\"}) by (ins)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "M Active Servers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgbouncer_pool_active_servers{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "M Active Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgbouncer_pool_active_clients{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "M Wait Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgbouncer_pool_waiting_clients{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S Max CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node:instance:cpu_usage{cls=\"$cls\", role=\"standby\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "CPU Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgb:instance:qps{cls=\"$cls\", role=\"standby\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg:instance:tps{cls=\"$cls\", role=\"standby\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S RT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 18 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pgb:instance:rt{cls=\"$cls\", role=\"standby\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Disk Free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S Max Backends",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pg_db_numbackends{ins=~\"\\\\d+\\\\.standby\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S Max Active Servers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pgbouncer_pool_active_servers{ins=~\"\\\\d+\\\\.standby\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S Max Active Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgbouncer_pool_active_clients{ins=~\"\\\\d+\\\\.standby\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S Wait Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgbouncer_pool_waiting_clients{ins=~\"\\\\d+\\\\.standby\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node:instance:disk_usage{cls=\"$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "CPU Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(pgbouncer_stat_total_query_count{cls=\"$cls\", datname!=\"pgbouncer\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cls) (irate(pg_db_xact_total{cls=\"$cls\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lag",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (cls) (pg_repl_replay_lag{cls=\"$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAL Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 21 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(pg_lsn{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Disk Free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DB Age",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 21 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pg_database_age{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_size_database{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Idle Xact",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_activity_count{state=~\"idle in transaction.*\", cls=\"$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "WAL Receiver",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "pg_standby_last_lsn{cls='$cls'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAL Sender",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 25 },
   "targets": [
    {
     "expr": "pg_repl_lsn{cls=\"$cls\"} - pg_repl_replay_lsn{cls=\"$cls\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication Lag Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_repl_lsn{cls=\"$cls\"} - pg_repl_replay_lsn{cls=\"$cls\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "[{{sync_state}}-{{state}}]{{ins}}->{{application_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication LSN Progress (Node has standbys)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 29 },
   "yaxes": [
    { "format": "hex" }
   ],
   "targets": [
    {
     "expr": "pg_repl_lsn{cls=\"$cls\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "pg_repl_replay_lsn{cls=\"$cls\"}",
     "legendFormat": "REPLAY-{{application_name}}"
    },
    {
     "expr": "pg_slot_restart_lsn{cls=\"$cls\"}",
     "legendFormat": "SLOT-{{slot_name}}"
    }
   ]
  },
  {
   "title": "Replication Lag Seconds (Sender's view)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_repl_replay_lag{cls=\"$cls\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "[{{sync_state}}-{{state}}]{{ins}}->{{application_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication Lag Second (Receiver's View)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_lag{cls=\"$cls\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication State Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_repl_state_count{cls=\"$cls\"} > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}-{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot Retained Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_slot_retained_bytes{cls=\"$cls\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{slot_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (node:instance:cpu_usage{cls=\"$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:instance:mem_usage{cls=\"$cls\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{cls=\"$cls\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load5{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (node:instance:disk_read{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\"})",
     "legendFormat": "Read-{{ins}}"
    },
    {
     "expr": "sum by (ins) (node:instance:disk_write{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\"})",
     "legendFormat": "Write-{{ins}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (node:instance:network_transmit{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\",device!~\"lo\"})",
     "legendFormat": "Transmit-{{ins}}"
    },
    {
     "expr": "sum by (ins) (node:instance:network_receive{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\",device!~\"lo\"})",
     "legendFormat": "Receive-{{ins}}"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg:instance:tps{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pgb:ins:qps{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rollbacks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (pg:instance:rollbacks{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"})",
     "legendFormat": "{{ins}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "pgb:ins:rt{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary QPS  Seasonality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgb:ins:qps{ins=\"$ins\"}",
     "legendFormat": "Today"
    },
    {
     "expr": "pgb:ins:qps{ins=\"$ins\"} OFFSET 1d",
     "legendFormat": "1D"
    },
    {
     "expr": "pgb:ins:qps{ins=\"$ins\"} OFFSET 2d",
     "legendFormat": "2D"
    }
   ]
  },
  {
   "title": "Standby QPS  Seasonality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pgb:ins:qps{ins=~\"\\\\d+\\\\.standby.$cls\"})",
     "legendFormat": "Today"
    },
    {
     "expr": "sum(pgb:ins:qps{ins=~\"\\\\d+\\\\.standby.$cls\"} OFFSET 1d)",
     "legendFormat": "1D"
    },
    {
     "expr": "sum(pgb:ins:qps{ins=~\"\\\\d+\\\\.standby.$cls\"} OFFSET 2d)",
     "legendFormat": "2D"
    }
   ]
  },
  {
   "title": "WAL Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(pg_lsn{ins=~\"\\\\d+\\\\.$cls\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "Buffer Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (ins)(increase(pg_db_blks_hit{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\"}[1m])) / sum by (ins)(increase(pg_db_blks_access{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\"}[1m]))",
     "legendFormat": "{{ins}}"
    }
   ]
  },
  {
   "title": "Tuples Returned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (irate(pg_db_tup_returned{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tuples Modified",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (irate(pg_db_tup_inserted{ins=\"$ins\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inserted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by (ins) (irate(pg_db_tup_updated{ins=\"$ins\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Updated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by (ins) (irate(pg_db_tup_deleted{ins=\"$ins\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deleted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary QPS / Standby QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(pgb:ins:qps{ins=~\"\\\\d+\\\\.(standby)\\\\.$cls$\"}) / sum(pgb:ins:qps{ins=~\"\\\\d+\\\\.(primary)\\\\.$cls$\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tuple Fetched / Tuple Modified",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pg_db_tup_fetched{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\"}[1m])) / sum(increase(pg_db_tup_modified{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls$\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Conflict", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Primary Locks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ins, mode) (pg_lock_count{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (ins, state) (pg_activity_max_tx_duration{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary Exclusive Locks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ins, mode) (pg_lock_count{ins=\"$ins\", mode=~\"AccessExclusiveLock|ExclusiveLock|ShareRowExclusiveLock|ShareLock|ShareUpdateExclusiveLock\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Idle in Xact",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{state=~\"idle in transaction.*\", ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Standby Locks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (pg_lock_count{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Conflict",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pg_db_confl_bufferpin{ins=~\"\\\\d+\\\\.$cls\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "BufferPin",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(pg_db_confl_deadlock{ins=~\"\\\\d+\\\\.$cls\"}[1m]))",
     "legendFormat": "Deadlock"
    },
    {
     "expr": "sum(increase(pg_db_confl_snapshot{ins=~\"\\\\d+\\\\.$cls\"}[1m]))",
     "legendFormat": "Snapshot"
    },
    {
     "expr": "sum(increase(pg_db_confl_lock{ins=~\"\\\\d+\\\\.$cls\"}[1m]))",
     "legendFormat": "Lock"
    },
    {
     "expr": "sum(increase(pg_db_confl_tablespace{ins=~\"\\\\d+\\\\.$cls\"}[1m]))",
     "legendFormat": "Tablespace"
    }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "Primary PG Backends",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_count{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PG Backends",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (pg_db_numbackends{ins=~\"\\\\d+\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary Pgbouncer Active Servers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pool_active_servers{ins=\"$ins\", datname!=\"pgbouncer\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}:{{user}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Pgbouncer Active Servers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (pgbouncer_pool_active_servers{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Primary Pgbouncer Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pool_active_clients{ins=\"$ins\", datname!=\"pgbouncer\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}:{{user}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Standby Pgbouncer Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (user) (pgbouncer_pool_active_clients{ins=~\"\\\\d+\\\\.standby\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{user}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Pgbouncer Active Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (pgbouncer_pool_active_clients{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Pgbouncer Waiting Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (pgbouncer_pool_waiting_clients{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  { "title": "Persist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 } },
  {
   "title": "Primary Buffer Flushed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(pg_bgwriter_buffers_checkpoint{ins=\"$ins\"}[1m]) * 8192",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "By Checkpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "irate(pg_bgwriter_buffers_backend{ins=\"$ins\"}[1m]) * 8192",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "By Backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "Buffer Flushed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 168 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(pg_bgwriter_buffers_checkpoint{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"}[1m])  +  irate(pg_bgwriter_buffers_backend{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"}[1m]))* 8192",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "Primary Buffer Alloc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(pg_bgwriter_buffers_alloc{ins=\"$ins\"}[1m]) * 8192",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocted Buffer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "Buffer Alloc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 175 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(pg_bgwriter_buffers_alloc{ins=~\"\\\\d+\\\\.(primary|standby)\\\\.$cls\"}[1m])* 8192",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "DB / WAL / Log Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_size_wal{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "WAL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "pg_database_size{ins=\"$ins\"}",
     "legendFormat": "DB-{{datname}}"
    },
    {
     "expr": "pg_size_log{ins=\"$ins\"}",
     "legendFormat": "Log"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "Size Delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 182 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "deriv(pg_size_wal{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "WAL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "deriv(pg_database_size{ins=\"$ins\"}[1m])",
     "legendFormat": "DB-{{datname}}"
    },
    {
     "expr": "deriv(pg_size_log{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "WAL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "Temp Bytes Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (rate(pg_db_temp_bytes{ins=~\"\\\\d+\\\\.$cls\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ins}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp File Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 189 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (ins) (increase(pg_db_temp_files{ins=~\"^\\\\d+\\\\.$cls$\"}[1m]))",
     "legendFormat": "{{ins}}"
    }
   ]
  },
  {
   "title": "Database Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 189 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "pg_database_age{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 } },
  {
   "title": "Primary Top 15 Query",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\"}[30m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Primary Query RT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(pg_query_total_time{ins=\"$ins\"}[5m]) / increase(pg_query_calls{ins=\"$ins\"}[5m])",
     "legendFormat": "{{query}}"
    }
   ]
  }
 ]
}