{
 "title": "PG Instance",
 "description": "PostgreSQL Instance Level Metrics",
 "tags": [
  "PG",
  "Instance"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Instance",
    "query": "label_values(pg_up{job=\"pg\"}, ins)"
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
   },
   { "name": "srv", "label": "Service" },
   {
    "name": "cls",
    "label": "Cluster",
    "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pg_up{ins=\"$ins\"}, role)"
   },
   {
    "name": "ip",
    "label": "IP",
    "query": "label_values(pg_up{ins=\"$ins\"} , ip)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_database_size{ins=\"$ins\"}, datname)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sequence",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "title": "Role",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "title": "Cluster",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "title": "Cluster ID",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Sibling Instances",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "pg_up{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "pg_database_size{ins=\"$ins\", datname!~\"template0|template1\"}"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_checkpoint_tli{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Recovery",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_in_recovery{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_standby_init_lsn{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Downstream",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pg_repl_lsn{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Network Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance) (node_network_up{ins=\"$ins\", device!=\"lo\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exporter Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (sum(absent(pg_up{ins=\"$ins\"})) or vector(0))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PG Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_up{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pgbouncer Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pgbouncer_up{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PG Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_uptime{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conf Reload",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_conf_reload_time{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Checksum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (pg_db_checksum_failures{ins=\"$ins\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node:instance:cpu_count{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "CPU Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node:instance:cpu_usage{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "CPU Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load 1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Load1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node:instance:mem_usage{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node:instance:swap_usage{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (instance) (node:instance:disk_usage{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Disk Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Exhaustion",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(- node_filesystem_avail_bytes{ins=\"$ins\", mountpoint=\"/\"} / deriv(node_filesystem_avail_bytes{ins=\"$ins\", mountpoint=\"/\"}[1h]) > 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Disk Free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (node_filesystem_free_bytes{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Free Space",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (irate(pg_db_xact_total{ins=\"$ins\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(pgbouncer_stat_total_query_count{ins=\"$ins\", datname!=\"pgbouncer\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "pgb:instance:rt{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Disk Free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Lag",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (instance) (pg_repl_lsn - pg_repl_replay_lsn{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Servers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (pgb:instance:active_servers{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backends",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg:instance:numbackends{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wait Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pgbouncer_pool_waiting_clients{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest Conn",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pg_activity_max_conn_duration{ins=\"$ins\"}) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (pg_size_database{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DB Age",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (instance)(pg_database_age{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Age Exhaustion",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min by (instance)((2147483648 - pg_database_age{ins=\"$ins\"}) / deriv(pg_database_age{ins=\"$ins\"}[1d]) > 0) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAL Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg:instance:wal_rate{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Disk Free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buffer Hit Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance)(increase(pg_db_blks_hit{ins=\"$ins\"}[1m])) / sum by (instance)(increase(pg_db_blks_access{ins=\"$ins\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rollback Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (irate(pg_db_xact_rollback{ins=\"$ins\"}[1m]))  / sum by (instance) (irate(pg_db_xact_total{ins=\"$ins\"}[1m])) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Idle In Xact",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (pg_activity_count{state=~\"idle in transaction.*\", ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest Xact",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (instance) (pg_activity_max_conn_duration{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ALERTS{ins=\"$ins\",alertstate=\"firing\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{alertname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "ALERTS{ins=\"$ins\"}"
    }
   ]
  },
  { "title": "Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Query Duration",
   "type": "graph",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(pg_exporter_query_scrape_duration{ins=\"$ins\"}[1m]) / increase(pg_exporter_query_scrape_total_count{ins=\"$ins\"}[1m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Scrape Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(pg_exporter_server_scrape_total_count{ins=\"$ins\"}[1m])",
     "legendFormat": "PG-Count"
    },
    {
     "expr": "increase(pg_exporter_server_scrape_error_count{ins=\"$ins\"}[1m])",
     "legendFormat": "PG-Error"
    },
    {
     "expr": "increase(pgbouncer_exporter_server_scrape_total_count{ins=\"$ins\"}[1m])",
     "legendFormat": "PGB-Count"
    },
    {
     "expr": "increase(pgbouncer_exporter_server_scrape_error_count{ins=\"$ins\"}[1m])",
     "legendFormat": "PGB-Error"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(pg_exporter_query_scrape_error_count{ins=\"$ins\"}[20s])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Metrics Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_exporter_query_scrape_metric_count{ins=\"$ins\"}",
     "legendFormat": "{{query}}"
    }
   ]
  },
  { "title": "OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Cache",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Buffers_bytes{ins=\"$ins\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{ins=\"$ins\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_PageTables_bytes{ins=\"$ins\"}",
     "legendFormat": "PageTable"
    },
    {
     "expr": "node_memory_Slab_bytes{ins=\"$ins\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_Shmem_bytes{ins=\"$ins\"}",
     "legendFormat": "Shmem"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Load1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_load5{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Load5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_load15{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Load15",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page In / Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_vmstat_pgpgin{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "PageIn",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "irate(node_vmstat_pgpgout{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "PageOut",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Context Switchs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{ins=\"$ins\"}[1m])",
     "legendFormat": "Read-{{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{ins=\"$ins\"}[1m])",
     "legendFormat": "Write-{{device}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_filefd_allocated{ins=\"$ins\"} / node_filefd_maximum{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:instance:network_transmit{ins=\"$ins\"}",
     "legendFormat": "Transmit-{{device}}"
    },
    {
     "expr": "node:instance:network_receive{ins=\"$ins\"}",
     "legendFormat": "Receive-{{device}}"
    }
   ]
  },
  {
   "title": "TCP Retransmit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{ins=\"$ins\"}[1m]) / (rate(node_netstat_Tcp_InSegs{ins=\"$ins\"}[1m]) + rate(node_netstat_Tcp_OutSegs{ins=\"$ins\"}[1m]))",
     "legendFormat": "Retransmit Rate"
    }
   ]
  },
  {
   "title": "Pgbouncer I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(pgbouncer_stat_total_sent{ins=\"$ins\", datname!=\"pgbouncer\"}[1m]))",
     "legendFormat": "OUT"
    },
    {
     "expr": "sum by (instance) (irate(pgbouncer_stat_total_received{ins=\"$ins\", datname!=\"pgbouncer\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "IN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_db_xact_total{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "QPS  Seasonality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(pgbouncer_stat_total_query_count{ins=\"$ins\", datname!=\"pgbouncer\"}[1m]))",
     "legendFormat": "Today"
    },
    {
     "expr": "sum by (instance) (irate(pgbouncer_stat_total_query_count{ins=\"$ins\", datname!=\"pgbouncer\"}[1m] OFFSET 1d))",
     "legendFormat": "1D"
    },
    {
     "expr": "sum by (instance) (irate(pgbouncer_stat_total_query_count{ins=\"$ins\", datname!=\"pgbouncer\"}[1m] OFFSET 2d))",
     "legendFormat": "2D"
    }
   ]
  },
  {
   "title": "Rollback",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_db_xact_rollback{ins=\"$ins\"}[1m])",
     "legendFormat": "{{datname}}-Count"
    },
    {
     "expr": "increase(pg_db_xact_rollback{ins=\"$ins\"}[1m]) /  increase(pg_db_xact_total{ins=\"$ins\"}[1m])",
     "legendFormat": "{{datname}}-Rate"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (increase(pgbouncer_stat_total_query_time{ins=\"$ins\", datname!=\"pgbouncer\"}[1m])) / sum by (instance)(increase(pgbouncer_stat_total_query_count{ins=\"$ins\", datname!=\"pgbouncer\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAL Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(pg_lsn{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "LSN Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "Buffer Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(increase(pg_db_blks_hit{ins=\"$ins\"}[1m])) / sum by (instance)(increase(pg_db_blks_access{ins=\"$ins\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tuples Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(pg_db_tup_fetched{ins=\"$ins\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by (instance) (irate(pg_db_tup_returned{ins=\"$ins\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Returned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tuples Modified",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(pg_db_tup_inserted{ins=\"$ins\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inserted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by (instance) (irate(pg_db_tup_updated{ins=\"$ins\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Updated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by (instance) (irate(pg_db_tup_deleted{ins=\"$ins\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deleted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Conflict", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, mode) (pg_lock_count{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exclusive Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, mode) (pg_lock_count{ins=\"$ins\", mode=~\"AccessExclusiveLock|ExclusiveLock|ShareRowExclusiveLock|ShareLock|ShareUpdateExclusiveLock\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Idle in Transaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_activity_count{state=~\"idle in transaction.*\", ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, state) (pg_activity_max_tx_duration{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "PG Backends",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (pg_db_numbackends{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pgbouncer Waiting Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pool_waiting_clients{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}:{{user}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "PG Backend State Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_count{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PG Backend Wait Event Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (event) (pg_wait_count{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{event}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Pool Servers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pool_active_servers{ins=\"$ins\", datname!=\"pgbouncer\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}:{{user}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Pgbouncer Server State Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (pgbouncer_pool_active_servers{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "sum by (instance) (pgbouncer_pool_idle_servers{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Idle",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "sum by (instance) ( pgbouncer_pool_used_servers{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Used",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "sum by (instance) (pgbouncer_pool_tested_servers{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Tested",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "sum by (instance) (pgbouncer_pool_login_servers{ins=\"$ins\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Login",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Active Pool Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pool_active_clients{ins=\"$ins\", datname!=\"pgbouncer\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}:{{user}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Pgbouncer Clients User Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (user) (pgbouncer_pool_active_clients{ins=\"$ins\", user!=\"pgbouncer\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{user}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "title": "Slaves",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 153 },
   "targets": [
    {
     "expr": "pg_repl_lsn{ins=\"$ins\"} - pg_repl_replay_lsn{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication Lag Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_repl_lsn{ins=\"$ins\"} - pg_repl_replay_lsn{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{application_name}}-{{client_addr}}-{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication LSN Progress (Node has standbys)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "hex" }
   ],
   "targets": [
    {
     "expr": "pg_repl_lsn{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "pg_repl_replay_lsn{ins=\"$ins\"}",
     "legendFormat": "{{application_name}}-{{client_addr}}"
    },
    {
     "expr": "pg_slot_restart_lsn{ins=\"$ins\"}",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "Replication Lag Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_repl_replay_lag{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{application_name}}-{{client_addr}}-{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication State Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_repl_state_count{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot Retained Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_slot_retained_bytes{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{slot_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Standby",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sender Host",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
     "format": "hex",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(pg_standby_init_lsn{ins=\"$ins\"}) by (host)"
      }
     ]
    },
    {
     "title": "Initial Timeline",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 3, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_standby_init_tli{ins=\"$ins\"}"
      }
     ]
    },
    {
     "title": "Initial LSN",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 9 },
     "format": "hex",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_standby_init_lsn{ins=\"$ins\"}"
      }
     ]
    },
    {
     "title": "Query Conflict",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (increase(pg_db_confl_bufferpin{ins=\"$ins\"}[1m]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "BufferPin",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum by (instance) (increase(pg_db_confl_deadlock{ins=\"$ins\"}[1m]))",
       "legendFormat": "Deadlock"
      },
      {
       "expr": "sum by (instance) (increase(pg_db_confl_snapshot{ins=\"$ins\"}[1m]))",
       "legendFormat": "Snapshot"
      },
      {
       "expr": "sum by (instance) (increase(pg_db_confl_lock{ins=\"$ins\"}[1m]))",
       "legendFormat": "Lock"
      },
      {
       "expr": "sum by (instance) (increase(pg_db_confl_tablespace{ins=\"$ins\"}[1m]))",
       "legendFormat": "Tablespace"
      }
     ]
    },
    {
     "title": "Lag to Upstream (Standby's View)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg_lag{ins=\"$ins\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sender Port",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(pg_standby_init_lsn{ins=\"$ins\"}) by (port)"
      }
     ]
    },
    {
     "title": "Latest Timeline",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 3, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_standby_last_tli{ins=\"$ins\"}"
      }
     ]
    },
    {
     "title": "Latest LSN",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 12 },
     "format": "hex",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_standby_last_lsn{ins=\"$ins\"}"
      }
     ]
    }
   ]
  },
  { "title": "Persist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 } },
  {
   "title": "Buffer Flushed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(pg_bgwriter_buffers_checkpoint{ins=\"$ins\"}[1m]) * 8192",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Flushed by Checkpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "irate(pg_bgwriter_buffers_backend{ins=\"$ins\"}[1m]) * 8192",
     "legendFormat": "Flushed by Backend"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "Buffer Allocated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(pg_bgwriter_buffers_alloc{ins=\"$ins\"}[1m]) * 8192",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocted Buffer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "DB / WAL / Log Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_size_wal{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "WAL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "pg_database_size{ins=\"$ins\"}",
     "legendFormat": "DB-{{datname}}"
    },
    {
     "expr": "pg_size_log{ins=\"$ins\"}",
     "legendFormat": "Log"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "Size Delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 183 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "deriv(pg_size_wal{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "WAL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "deriv(pg_database_size{ins=\"$ins\"}[1m])",
     "legendFormat": "DB-{{datname}}"
    },
    {
     "expr": "deriv(pg_size_log{ins=\"$ins\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "WAL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_timed{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointTimed"
    },
    {
     "expr": "increase(pg_bgwriter_checkpoints_req{ins=\"$ins\"}[1m])",
     "legendFormat": "CheckpointRequested"
    }
   ]
  },
  {
   "title": "Temp Bytes Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,datname) (rate(pg_db_temp_bytes{ins=\"$ins\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp File Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 190 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,datname) (irate(pg_db_temp_files{ins=\"$ins\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Database Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 190 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "pg_database_age{ins=\"$ins\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 197 } },
  {
   "title": "Query Issued (Top 15)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_query_calls{ins=\"$ins\"}[5m]) / 300",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Query Mean Time (realtime)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(pg_query_total_time{ins=\"$ins\"}[5m]) / increase(pg_query_calls{ins=\"$ins\"}[5m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Query Rows Touched",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_query_rows{ins=\"$ins\"}[5m]) / 300",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Query Mean Time (cumulative)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_query_mean_time{ins=\"$ins\"}",
     "legendFormat": "{{query}}"
    }
   ]
  }
 ]
}